export const dummyData = [
  {
    id: 0,
    name: "Haoran Li",
    role: "Java Developer",
    status: "New",
    progress: "0%",
    date: "28 October 2020",
  },
  {
    id: 1,
    name: "Yubxuan Sun",
    role: "Web Developer",
    status: "Pending",
    progress: "90%",
    date: "8 October 2020",
  },
  {
    id: 2,
    name: "Haoran Li",
    role: ".Net Developer",
    status: "New",
    progress: "30%",
    date: "28 October 2020",
  },
  {
    id: 3,
    name: "Yubxuan Sun",
    role: "Web Developer",
    status: "Pending",
    progress: "90%",
    date: "8 October 2020",
  },
  {
    id: 4,
    name: "Haoran Li",
    role: "Java Developer",
    status: "New",
    progress: "50%",
    date: "28 October 2020",
  },
  {
    id: 5,
    name: "Yubxuan Sun",
    role: "Web Developer",
    status: "Pending",
    progress: "90%",
    date: "8 October 2020",
  },
  {
    id: 6,
    name: "Haoran Li",
    role: ".Net Developer",
    status: "New",
    progress: "60%",
    date: "28 October 2020",
  },
  {
    id: 7,
    name: "Yubxuan Sun",
    role: "Web Developer",
    status: "Pending",
    progress: "90%",
    date: "8 October 2020",
  },
  {
    id: 8,
    name: "Haoran Li",
    role: "Java Developer",
    status: "New",
    progress: "70%",
    date: "28 October 2020",
  },
];
